DROP TABLE IF EXISTS TEST_TABLE;
CREATE TABLE TEST_TABLE ( 
ID INTEGER IDENTITY
, INTEGER_ INTEGER
, DOUBLE_ DOUBLE
, DATE_ DATE 
, TIME_ TIME
, VARCHAR_ VARCHAR(252)  
, CHAR_ CHAR(50)
, CLOB_ LONGVARCHAR 
); 
